apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: flux-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: AKIAW3MEFWWHLJNM6K6D
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: us-east-1 # the region you want