apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: stag
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/phosphor-v/webserver-ec2-module-terraform
  ref:
    branch: stag
  secretRef:
    name: flux-system
