apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: tf-app
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket         = "phosphor-tfstate"
        key            = "week10/terraform.tfstate"
        region         = "us-east-1"
        encrypt        = true
      }