apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/denis-dovgodko/webserver-ec2-module-terraform
  ref:
    branch: main
  secretRef:
    name: flux-system