apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: $CIRCLE_BRANCH
  namespace: flux-system
spec:
  vars:
  - name: environment_name
    value: $CIRCLE_BRANCH
  interval: 1m
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: $CIRCLE_BRANCH
  approvePlan: auto
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket = "week10flux"
        key = "${CIRCLE_BRANCH}/terraform.tfstate"
        region = "us-east-1"
      }
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: aws-credentials